name: Build and Test
on: push
jobs:
  Test:    
    runs-on: ubuntu-latest
    name: Checkout, Build and Test
    steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
        - name: Install Dotnet
          uses: actions/setup-dotnet@v4.0.0
        - name: Restore dependencies
          run: dotnet restore GHActions.sln
        - name: Build and Test
          run: |
            dotnet build GHActions.sln
            dotnet test GHActions.sln
