name: Deploy Project
on: [push, workflow_dispatch]
jobs:
  test:    
    runs-on: ubuntu-latest
    name: Test
    steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
        - name: Install Dotnet
          uses: actions/setup-dotnet@v4.0.0
        - name: Restore dependencies
          run: dotnet restore GHActions.sln
        - name: Test
          run:  dotnet test GHActions.sln            
  deploy:
      needs: test
      name: Build and Deploy
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
        - name: Install Dotnet
          uses: actions/setup-dotnet@v4.0.0
        - name: Restore dependencies
          run: dotnet restore GHActions.sln
        - name: Build project
          run: dotnet build GHActions.sln
        - name: Deploy
          run: echo Deploying...
