name: Deploy Project
on: 
  pull_request:
    types: [opened, edited]
  workflow_dispatch: 
  push:
    branches:
    - main
jobs:
  test:    
    runs-on: ubuntu-latest
    name: Test
    steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
        - name: Install Dotnet
          uses: actions/setup-dotnet@v4.0.0
        - name: Restore dependencies
          run: dotnet restore GHActions.sln
        - name: Test
          run:  dotnet test GHActions.sln            
  build:
      needs: test
      name: Build
      runs-on: ubuntu-latest
      outputs: 
        gha-file: ${{ steps.publish.outputs.file }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
        - name: Install Dotnet
          uses: actions/setup-dotnet@v4.0.0
        - name: Restore dependencies
          run: dotnet restore GHActions.sln
        - name: Build project
          run: dotnet build GHActions.sln
        - name: Upload artifacts       
          uses: actions/upload-artifact@v3
          with:
            name: dll-files
            path: | 
              ./GHActions/bin/Debug/net8.0
              package.nuget
        - name: Publish Package Name
          id: publish
          run: find GHActions\bin\Debug\net8.0\GHActions.dll -type f -execdir echo 'file={}' >> $GITHUB_OUTPUT ';'
  deploy:
      needs: build
      name: Deploy
      runs-on: ubuntu-latest              
      steps:
        - name: Get build artifacts
          uses: actions/download-artifact@v3
          with:
            name: dll-files
        - name: Output contents
          run: ls
        - name: Output filename
          run: echo $${{ needs.build.outputs.gha-file }}
        - name: Deploy
          run: echo "Deploying..."
          
