name: Output information
on: workflow_dispatch
jobs:
    info:
        name: Information
        runs-on: ubuntu-latest
        steps:
            - name: Output Github Context
              run: echo "${{ toJSON(github) }}"
